### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by hboon** [alpha-wallet/ethereum-attestation#4]
https://github.com/alpha-wallet/ethereum-attestation/blob/master/paper/attestation.tex#L111:

> We a comma separated list within parenthesis to denote an unspecified binary encoding of elements, i.e. $(a, b, c)$ is actually a bitstring encoding the values $a$, $b$, and $c$ in some deterministic manner. 

"We use a comma separated"

**Comment by colourful-land** [comment]
Solved!
